/**
 * @file  ActorFactoryData.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
#include "ActorDefinitionIdentifier.hpp"
#include "ActorDefinitionGroup.hpp"
#include "EntityContext.hpp"
#include <optional>
using ActorFactoryFunction = std::unique_ptr<Actor>(*)(ActorDefinitionGroup*, const ActorDefinitionIdentifier&,class EntityContext&);
#undef BEFORE_EXTRA

/**
 * @brief MC structure ActorFactoryData.
 *
 */
struct ActorFactoryData {

#define AFTER_EXTRA
#define DISABLE_CONSTRUCTOR_PREVENTION_ACTORFACTORYDATA
public:
    ActorDefinitionIdentifier mIdentifier;
    ActorDefinitionIdentifier mBaseIdentifier;
    bool mAllowSummon;
    ActorFactoryFunction mFactory;
    std::optional<int> mExperimentIndex;
    ActorType mActorType;
    float mWalkAnimSpeed;
    bool unk384 = false;


#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ACTORFACTORYDATA
public:
    ActorFactoryData(struct ActorFactoryData const &) = delete;
    ActorFactoryData() = delete;
#endif

public:
    /**
     * @symbol ??4ActorFactoryData@@QEAAAEAU0@AEBU0@@Z
     * @hash   -2099543946
     */
    MCAPI struct ActorFactoryData & operator=(struct ActorFactoryData const &);
    /**
     * @symbol ??1ActorFactoryData@@QEAA@XZ
     * @hash   1730962777
     */
    MCAPI ~ActorFactoryData();

};