/**
 * @file  ActorMapping.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here
#include "HashedString.hpp"
#undef BEFORE_EXTRA

/**
 * @brief MC structure ActorMapping.
 *
 */
struct ActorMapping {

#define AFTER_EXTRA
    // Add Member There
#define DISABLE_CONSTRUCTOR_PREVENTION_ACTORMAPPING
public:
    std::string mNamespace;
    std::string mPrimaryName;
    std::string mAlternateName;
    HashedString mCanonicalName;

    ActorMapping(const ActorMapping&) = default;
    ActorMapping(ActorMapping&&) = default;

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ACTORMAPPING
public:
    struct ActorMapping& operator=(struct ActorMapping const &) = delete;
    ActorMapping(struct ActorMapping const &) = delete;
    ActorMapping() = delete;
#endif

public:
    /**
     * @symbol ??0ActorMapping@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z
     * @hash   -247934068
     */
    MCAPI ActorMapping(std::string const &, std::string const &);
    /**
     * @symbol ??0ActorMapping@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z
     * @hash   339514220
     */
    MCAPI ActorMapping(std::string const &, std::string const &, std::string const &);
    /**
     * @symbol ?getMappingName@ActorMapping@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ActorTypeNamespaceRules@@@Z
     * @hash   -1596062925
     */
    MCAPI std::string getMappingName(enum class ActorTypeNamespaceRules) const;
    /**
     * @symbol ??1ActorMapping@@QEAA@XZ
     * @hash   2024913731
     */
    MCAPI ~ActorMapping();

};